server:
  http:
    addr: 0.0.0.0:8755
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9300
    timeout: 1s
data:
  database:
    source: root:dangerous@tcp(127.0.0.1:3306)/realowrld01?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    db: 0
registry:
  consul:
    address: 127.0.0.1:8500
    scheme: http
trace:
  endpoint: http://127.0.0.1:14268/api/traces
service:
  user:
    endpoint: discovery:///knsh.user.service

