// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"meeting/internal/biz"
	"meeting/internal/conf"
	"meeting/internal/data"
	"meeting/internal/server"
	"meeting/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	meetingRepo := data.NewMeetingRepo(dataData, logger)
	meetingGreeterUsecase := biz.NewMeetingGreeterUsecase(meetingRepo, logger)
	meetingService := service.NewMeetingService(meetingGreeterUsecase)
	httpServer := server.NewHTTPServer(confServer, meetingService, logger)
	grpcServer := server.NewGRPCServer(confServer, meetingService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
